### ISSUE TITLE
Reverse Geocoding Not returning Custom Layers

### ISSUE THREAD

**Issue by toton6868** [pelias/documentation#259] opened 2019-08-21 09:45 UTC
I have added a CSV file with the help of csv-importer. In the names field, I have a few mobiles no. which starts with `01`  I used the source as **`csv`** and layers as **`custom`**. I have configured the API parameters of my Config.json as follows

```
"api": {
    "accessLog": "common",
    "textAnalyzer": "libpostal",
    "host": "http://pelias.mapzen.com/",
    "indexName": "pelias",
    "version": "1.0",
    "targets": {
      "auto_discover": false,
      "canonical_sources": ["whosonfirst", "openstreetmap", "openaddresses", "geonames", "csv"],
      "layers_by_source": {
        "openstreetmap": [ "address", "venue", "street" ],
        "openaddresses": [ "address" ],
        "geonames": [
          "country", "macroregion", "region", "county", "localadmin", "locality", "borough",
          "neighbourhood", "venue"
        ],
        "whosonfirst": [
          "continent", "empire", "country", "dependency", "macroregion", "region", "locality",
          "localadmin", "macrocounty", "county", "macrohood", "borough", "neighbourhood",
          "microhood", "disputed", "venue", "postalcode", "continent", "ocean", "marinearea"
        ],
        "csv": ["custom"]
      },
      "source_aliases": {
        "osm": [ "openstreetmap" ],
        "oa":  [ "openaddresses" ],
        "gn":  [ "geonames" ],
        "wof": [ "whosonfirst" ],
        "csv": [ "csv" ]
      },
      "layer_aliases": {
        "coarse": [
          "continent", "empire", "country", "dependency", "macroregion", "region", "locality",
          "localadmin", "macrocounty", "county", "macrohood", "borough", "neighbourhood",
          "microhood", "disputed", "postalcode", "continent", "ocean", "marinearea", "custom"
        ]
      },
      "csv": ["custom"]
    },
    "services": {
      "placeholder": {
        "url": "http://localhost:3101"
      },
      "libpostal": {
        "url": "http://localhost:3103"
      },
      "pip": {
        "url": "http://localhost:3102"
      },
      "interpolation": {
        "url": "http://localhost:3104"
      }
    }
  },
```

When I am working with the search API it's working great and returning the correct data. The problem is in Autocomplete and Reverse APIs.

In reverse API the custom layer is not returning any data. if I use `&layers=custom` its returning null data. 

In Autocomplete API If I put `0171` its not returning any data but when I am entering full mobile no such as `01712345678` it's returning only one data. Thus I am unable to use it in Autocomplete.

**Comment by orangejulius** [comment] 2019-08-22 21:46
Hi @toton6868,
This looks like a duplicate of https://github.com/pelias/api/issues/1342.

Please avoid opening duplicate issues if you can. It adds extra work for us to maintain the project. It won't get you an answer any faster.

**Closed by orangejulius** 2019-08-22 21:46 UTC

**Comment by toton6868** [comment] 2019-08-22 23:09
I am really sorry. Actually, I have opened it first then I realize this is not the right repo to ask this related question and I didn't find any delete option. Really sorry.
